// react/src/components/list/List.tsx
import { useState } from 'react'
import { ListContext } from './context'

type ListProps = {
	children: React.ReactNode
	listItems: any[]
}

export function List({ children, listItems }: ListProps) {
	const [items, setListItems] = useState(listItems)

	function addItem() {
		setListItems((items) => [...items, items.length + 1])
	}

	function removeItem() {
		setListItems((items) =>
			items.slice(0, items.length - 1)
		)
	}

	return (
		<ListContext.Provider
			value={{ items, addItem, removeItem }}
		>
			<ul>{children}</ul>
		</ListContext.Provider>
	)
}

// svelte/src/lib/list/List.svelte
<script lang="ts">
	import { setContext } from 'svelte'
	import { writable, type Writable } from 'svelte/store'
	export let listItems: any[]

	const items = writable(listItems)

	setContext('items', items)
	setContext('addItem', addItem)
	setContext('removeItem', removeItem)

	function addItem() {
		$items = [...$items, $items.length + 1]
	}

	function removeItem() {
		$items = $items.slice(0, $items.length - 1)
	}
</script>

<ul>
	<slot />
</ul>
