// svelte/src/lib/Synchronization.svelte
<script lang="ts">
	import ein from '../assets/video.mp4'

	let videoEl: HTMLVideoElement = null
	let status: 'paused' | 'playing' = 'paused'

	function play() {
		videoEl.play()
		status = 'playing'
	}

	function pause() {
		videoEl.pause()
		status = 'paused'
	}

	function handleClick() {
		status === 'paused' ? play() : pause()
	}
</script>

<!-- svelte-ignore a11y-media-has-caption -->
<video bind:this={videoEl} src={ein} loop />

<button on:click={handleClick}>
	{status === 'paused' ? 'Play' : 'Pause'}
</button>

// react/src/components/Synchronization.tsx
import { useEffect, useRef, useState } from 'react'
import ein from '../assets/video.mp4'

type Status = 'paused' | 'playing'

export default function Player() {
	const [status, setStatus] = useState<Status>('paused')
	const videoEl = useRef<HTMLVideoElement>(null)

	useEffect(() => {
		status === 'paused' ? pause() : play()
	}, [status])

	function play() {
		videoEl.current?.play()
	}

	function pause() {
		videoEl.current?.pause()
	}

	function handleClick() {
		setStatus(status === 'paused' ? 'playing' : 'paused')
	}

	return (
		<>
			<video ref={videoEl} src={ein} loop />

			<button onClick={handleClick}>
				{status === 'paused' ? 'Play' : 'Pause'}
			</button>
		</>
	)
}
